sonar_diag:
  ros__parameters:
    # Connection
    sonar_ip: "192.168.32.109"
    udp_mode: "unicast"
    interface_ip: "192.168.32.190"
    unicast_destination_ip: "192.168.32.190"
    unicast_destination_port: 4747

    # Diagnostics mode
    # Set test_switch to true to run mode-switch latency test
    test_switch: false
    cycles: 3
